# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1309783916);
user_pref("app.update.lastUpdateTime.background-update-timer", 1309784079);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1309784011);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1309784004);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1309783628);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1309850161);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.17");
user_pref("extensions.enabledItems", "{CAFEEFAC-0016-0000-0025-ABCDEFFEDCBA}:6.0.25,{22C7F6C6-8D67-4534-92B5-529A0EC09405}:5.8.0.1092,esnipsxpi@logia.esnips:1.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.17");
user_pref("extensions.lastAppVersion", "3.6.17");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.disable_button.openCertManager", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1312375036);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
